### ISSUE TITLE
Add an open_spiel game wrapper

### ISSUE THREAD

**Issue by ChessProfessorX** [goshawk22/alpha-zero-chess#1]
I saw your muzero-general repo. It had an open_spiel game wrapper. Can you please add it here too?
Keras is kinda slow.

Also all games result in a draw. So no new model is selected.

**Comment by goshawk22** [comment]
The open_spiel library currently doesn't have a function for getCanonicalBoard. I can't seem to get a workaround working, but feel free to try. As far as I am aware, this is the only part that needs fixing.
See https://github.com/deepmind/open_spiel/issues/472

**Comment by ChessProfessorX** [comment]
So did they add a function for getCanonicalBoard?

**Comment by goshawk22** [comment]
I don't think so - the issue is still open.
